# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 12:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django_extensions.db.fields
import django_revision.revision_field
import edc_base.model.fields.hostname_modification_field
import edc_base.model.fields.userfield
import edc_base.model.fields.uuid_auto_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('user_created', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user created')),
                ('user_modified', edc_base.model.fields.userfield.UserField(editable=False, max_length=50, verbose_name='user modified')),
                ('hostname_created', models.CharField(default='mac2-2.local', editable=False, help_text='System field. (modified on create only)', max_length=50)),
                ('hostname_modified', edc_base.model.fields.hostname_modification_field.HostnameModificationField(editable=False, help_text='System field. (modified on every save)', max_length=50)),
                ('revision', django_revision.revision_field.RevisionField(blank=True, editable=False, help_text='System field. Git repository tag:branch:commit.', max_length=75, null=True, verbose_name='Revision')),
                ('id', edc_base.model.fields.uuid_auto_field.UUIDAutoField(editable=False, help_text='System field. UUID primary key.', primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=50)),
                ('attribute', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('[a-z0-9_]', 'Invalid attribute name, must be lower case separated by underscore.')])),
                ('value', models.CharField(help_text='any string value or string representation of a value', max_length=50)),
                ('convert', models.BooleanField(default=True, help_text='If True, automatically convert string value to its datatype. Type is autodetected in this order: Boolean, None, Decimal, Integer, Date, Datetime otherwise String')),
                ('comment', models.CharField(max_length=100)),
            ],
        ),
    ]
